#ifndef HARBOR_MMIO_REGISTER_FILE_MAP_H
#define HARBOR_MMIO_REGISTER_FILE_MAP_H

#include <stdint.h>

#define HARBOR_MMIO_REGISTER_FILE_BASE UINT64_C(0x10010000)
#define HARBOR_MMIO_REGISTER_FILE_REGISTER_COUNT 16U
#define HARBOR_MMIO_REGISTER_FILE_REGISTER_WIDTH_BYTES 4U
#define HARBOR_MMIO_REGISTER_FILE_ADDRESS_SPAN_BYTES \
    (HARBOR_MMIO_REGISTER_FILE_REGISTER_COUNT * HARBOR_MMIO_REGISTER_FILE_REGISTER_WIDTH_BYTES)

#endif // HARBOR_MMIO_REGISTER_FILE_MAP_H
