#ifndef HARBOR_MMIO_REGISTER_FILE_MAP_H
#define HARBOR_MMIO_REGISTER_FILE_MAP_H

#include <stdint.h>

/*
 * Register-file map configuration:
 *
 * - HARBOR_MMIO_REGISTER_FILE_BASE defines the guest physical base address.
 * - HARBOR_MMIO_REGISTER_FILE_REGISTER_COUNT defines the number of 32-bit registers.
 * - Constant registers are configured by adding
 *   HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_N_INDEX and
 *   HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_N_VALUE pairs.
 * - Keep HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_COUNT,
 *   HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_MASK, and
 *   harbor_mmio_register_file_constant_register_value() in sync with the
 *   configured constant register pairs.
 *
 * Writes to constant registers are accepted by the register-file model, but the
 * stored value remains the configured constant value.
 */

#define HARBOR_MMIO_REGISTER_FILE_BASE UINT64_C(0x10010000)
#define HARBOR_MMIO_REGISTER_FILE_REGISTER_COUNT 16U
#define HARBOR_MMIO_REGISTER_FILE_REGISTER_WIDTH_BYTES 4U
#define HARBOR_MMIO_REGISTER_FILE_ADDRESS_SPAN_BYTES (HARBOR_MMIO_REGISTER_FILE_REGISTER_COUNT * HARBOR_MMIO_REGISTER_FILE_REGISTER_WIDTH_BYTES)

#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_COUNT 3U

#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_0_INDEX 0U
#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_0_VALUE UINT32_C(0x48425200)

#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_1_INDEX 1U
#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_1_VALUE UINT32_C(0x00010000)

#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_2_INDEX 2U
#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_2_VALUE UINT32_C(0xdeadbeef)

#define HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_MASK \
    ((UINT32_C(1) << HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_0_INDEX) | \
     (UINT32_C(1) << HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_1_INDEX) | \
     (UINT32_C(1) << HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_2_INDEX))

static inline int harbor_mmio_register_file_is_constant_register_index(uint32_t index)
{
    return (index < HARBOR_MMIO_REGISTER_FILE_REGISTER_COUNT) &&
           ((HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_MASK & (UINT32_C(1) << index)) != 0U);
}

static inline uint32_t harbor_mmio_register_file_constant_register_value(uint32_t index)
{
    switch (index) {
    case HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_0_INDEX:
        return HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_0_VALUE;
    case HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_1_INDEX:
        return HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_1_VALUE;
    case HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_2_INDEX:
        return HARBOR_MMIO_REGISTER_FILE_CONSTANT_REGISTER_2_VALUE;
    default:
        return UINT32_C(0);
    }
}

#endif // HARBOR_MMIO_REGISTER_FILE_MAP_H
